### ISSUE TITLE
Importing plugin cluster_connect.py failed: When using gi.repository you must not import static modules like "gobject". Please change all occurrences of "import gobject" to "from gi.repository import GObject".

### ISSUE THREAD

**Issue by joernott** [dr1s/terminator-plugins#2]
When I tried to get the latest version of the cluster_connect plugin to work with terminator 0.98 on a RHEL 7.3 machine with python 2.7.5, I am getting the error message

> PluginRegistry::load_plugins:  Importing plugin cluster_connect.py failed: When using gi.repository you must not import static modules like "gobject". Please change all occurrences of "import gobject" to "from gi.repository import GObject".

Initially, it seemed to be caused by commit a4761ead3f7ccd6a3fcbe089c1c241fb8597ffb7, but re-adding this line still causes the above error to pop up. It turned out to be commit 229e01c98e5325d44002acff34ce261fd30601dd causing the problem with the switch to GTK3.

Using the file from d0db9a15bcedc5f5ed295178ef9aa41aaffa310d solved the issue.

**Comment by dr1s** [comment]
Thanks for the report. Which version of terminator are you using? GTK2 or GTK3?

The master branch will only work with the GTK3 version of terminator, but you can find the GTK2 version in the branch 'gtk2'. This version corresponds with the commit you're referencing.

**Comment by joernott** [comment]
The EPEL rpm 0.98-3 (which is quite old) for terminator references gtk2 as dependency, so this is most likely the gtk2 version.

I must have missed that. It could be helpful to add that info to the Readme.md.

**Comment by dr1s** [comment]
Thank you for your help, I added it as soon as I saw your issue.
